<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Enexis.KabelChecker.Core</AssemblyName>
    <RootNamespace>Enexis.KabelChecker.Core</RootNamespace>
  </PropertyGroup>
</Project>
